#!/usr/bin/env julia
# Generate CLI reference docs, completions, and inventory from the registry.
#
# Usage:
#   julia --project docs/generate_cli_reference.jl           # write artifacts
#   julia --project docs/generate_cli_reference.jl --check   # fail if stale
#   julia --project docs/generate_cli_reference.jl --claude-md  # also patch CLAUDE.md if present

using Friedman
using Dates

const ROOT = dirname(@__DIR__)
const CHECK = "--check" in ARGS
const DO_CLAUDE = "--claude-md" in ARGS || !CHECK

# ── Collect specs ──────────────────────────────────────────────

function _all_specs()::Vector{Friedman.CommandSpec}
    # Prefer REGISTRY (populated by register_* during build_app); fall back to walking APP
    specs = copy(Friedman.REGISTRY)
    if isempty(specs)
        error("REGISTRY is empty — was build_app() run?")
    end
    # Dedup by path (in case build_app called more than once in a session)
    seen = Set{Vector{String}}()
    out = Friedman.CommandSpec[]
    for s in specs
        s.path in seen && continue
        push!(seen, s.path)
        push!(out, s)
    end
    return out
end

function _group_by_top(specs::Vector{Friedman.CommandSpec})
    groups = Dict{String,Vector{Friedman.CommandSpec}}()
    for s in specs
        isempty(s.path) && continue
        top = s.path[1]
        push!(get!(groups, top, Friedman.CommandSpec[]), s)
    end
    return groups
end

function _fmt_default(d)
    isnothing(d) && return "—"
    d isa String && isempty(d) && return "`\"\"`"
    return "`$(d)`"
end

function _fmt_choices(c)
    isnothing(c) && return "—"
    return join("`" .* c .* "`", ", ")
end

function _type_name(t::Type)
    t === Nothing && return "Any"
    return string(t)
end

# ── Markdown emitters ─────────────────────────────────────────

"""
    _md_cell(s) -> String

Escape a value destined for a markdown TABLE CELL. An unescaped `|` ends the cell, so any
description carrying one silently splits into extra columns and the row renders corrupt.
Command descriptions are full of them — `table|csv|json`, `cholesky|sign|narrative|…` —
so every generated page had broken `--format` and `--id` rows before this was escaped.
"""
_md_cell(s) = replace(string(s), "|" => "\\|")

function _leaf_md(spec::Friedman.CommandSpec)::String
    io = IOBuffer()
    path = join(spec.path, " ")
    println(io, "### `friedman $path`")
    println(io)
    println(io, spec.summary)
    println(io)
    if !isempty(spec.args)
        println(io, "| Argument | Type | Required | Default | Description |")
        println(io, "|----------|------|----------|---------|-------------|")
        for a in spec.args
            req = a.required ? "yes" : "no"
            println(io, "| `$(a.name)` | `$(_type_name(a.type))` | $req | $(_fmt_default(a.default)) | $(_md_cell(a.description)) |")
        end
        println(io)
    end
    if !isempty(spec.options)
        println(io, "| Option | Short | Type | Default | Choices | Description |")
        println(io, "|--------|-------|------|---------|---------|-------------|")
        for o in spec.options
            short = isempty(o.short) ? "—" : "`-$(o.short)`"
            println(io, "| `--$(o.name)` | $short | `$(_type_name(o.type))` | $(_fmt_default(o.default)) | $(_fmt_choices(o.choices)) | $(_md_cell(o.description)) |")
        end
        println(io)
    end
    if !isempty(spec.flags)
        println(io, "| Flag | Short | Description |")
        println(io, "|------|-------|-------------|")
        for f in spec.flags
            short = isempty(f.short) ? "—" : "`-$(f.short)`"
            println(io, "| `--$(f.name)` | $short | $(_md_cell(f.description)) |")
        end
        println(io)
    end
    if !isempty(spec.tables)
        println(io, "**Output tables:** ", join(["`$(t.name)` ($(t.description))" for t in spec.tables], "; "))
        println(io)
    end
    return String(take!(io))
end

function _top_page(top::String, leaves::Vector{Friedman.CommandSpec})::String
    io = IOBuffer()
    println(io, "<!-- GENERATED by docs/generate_cli_reference.jl — do not hand-edit -->")
    println(io, "# `$top`")
    println(io)
    println(io, "Generated reference for `friedman $top` and its subcommands.")
    println(io)
    println(io, "**Leaves:** $(length(leaves))")
    println(io)
    for spec in sort(leaves; by=s -> join(s.path, " "))
        print(io, _leaf_md(spec))
        println(io, "---")
        println(io)
    end
    return String(take!(io))
end

function _tree_text(specs::Vector{Friedman.CommandSpec})::String
    groups = _group_by_top(specs)
    tops = sort(collect(keys(groups)))
    io = IOBuffer()
    println(io, "friedman")
    for (i, top) in enumerate(tops)
        leaves = groups[top]
        names = String[]
        for s in leaves
            if length(s.path) == 2
                push!(names, s.path[2])
            elseif length(s.path) >= 3
                push!(names, join(s.path[2:end], " "))
            end
        end
        unique!(names)
        sort!(names)
        branch = i == length(tops) ? "└──" : "├──"
        # wrap names
        line = "$branch $top"
        if !isempty(names)
            line *= "     " * join(names, " | ")
        end
        println(io, line)
    end
    n_leaves = length(specs)
    n_tops = length(tops)
    println(io)
    println(io, "Total: $n_tops top-level commands, $n_leaves leaves (from registry).")
    return String(take!(io))
end

function _overview_md(specs::Vector{Friedman.CommandSpec})::String
    io = IOBuffer()
    println(io, "# CLI Reference Overview")
    println(io)
    println(io, "Friedman-cli uses an **action-first** command hierarchy: commands are organized by action (`estimate`, `irf`, `forecast`, ...) rather than by model type.")
    println(io)
    println(io, "<!-- BEGIN GENERATED: do not hand-edit; run julia docs/generate_cli_reference.jl -->")
    println(io)
    println(io, "## Command Tree")
    println(io)
    println(io, "```")
    print(io, _tree_text(specs))
    println(io, "```")
    println(io)
    println(io, "Additionally, `friedman repl` launches an interactive REPL session with persistent data loading, result caching, and tab completion.")
    println(io)
    println(io, "## Generated reference pages")
    println(io)
    groups = _group_by_top(specs)
    for top in sort(collect(keys(groups)))
        println(io, "- [`$top`](generated/$top.md) — $(length(groups[top])) leaves")
    end
    println(io)
    println(io, "<!-- END GENERATED -->")
    println(io)
    println(io, "## Common Options")
    println(io)
    println(io, "All commands that produce output support these options:")
    println(io)
    println(io, "| Option | Short | Type | Default | Description |")
    println(io, "|--------|-------|------|---------|-------------|")
    println(io, "| `--format` | `-f` | String | `table` | Output format: `table`, `csv`, or `json` |")
    println(io, "| `--output` | `-o` | String | (stdout) | Export results to a file path |")
    println(io)
    println(io, "## Help")
    println(io)
    println(io, "Every command and subcommand supports `--help`. Machine-readable schema:")
    println(io)
    println(io, "```bash")
    println(io, "friedman schema estimate var")
    println(io, "```")
    return String(take!(io))
end

function _claude_block(specs::Vector{Friedman.CommandSpec})::String
    io = IOBuffer()
    println(io, "<!-- BEGIN GENERATED: do not hand-edit; run julia docs/generate_cli_reference.jl --claude-md -->")
    println(io, "Generated: $(Dates.now()) UTC")
    println(io)
    println(io, "### Registry inventory")
    println(io)
    println(io, "- Leaves: **$(length(specs))**")
    groups = _group_by_top(specs)
    println(io, "- Top-level: **$(length(groups))** — ", join(sort(collect(keys(groups))), ", "))
    println(io)
    println(io, "### Command tree")
    println(io)
    println(io, "```")
    print(io, _tree_text(specs))
    println(io, "```")
    println(io, "<!-- END GENERATED -->")
    return String(take!(io))
end

# ── Shell completions ─────────────────────────────────────────

function _bash_completion(specs::Vector{Friedman.CommandSpec})::String
    groups = _group_by_top(specs)
    tops = sort(collect(keys(groups)))
    io = IOBuffer()
    println(io, "# Friedman-cli bash completion (generated)")
    println(io, "_friedman() {")
    println(io, "  local cur prev words cword")
    println(io, "  _init_completion || return")
    println(io, "  if [[ \$cword -eq 1 ]]; then")
    println(io, "    COMPREPLY=( \$(compgen -W \"$(join(tops, " ")) repl\" -- \"\$cur\") )")
    println(io, "    return")
    println(io, "  fi")
    println(io, "  case \"\${words[1]}\" in")
    for top in tops
        leaves = sort(unique([s.path[2] for s in groups[top] if length(s.path) >= 2]))
        println(io, "    $top) COMPREPLY=( \$(compgen -W \"$(join(leaves, " "))\" -- \"\$cur\") ) ;;")
    end
    println(io, "  esac")
    println(io, "}")
    println(io, "complete -F _friedman friedman")
    return String(take!(io))
end

function _zsh_completion(specs::Vector{Friedman.CommandSpec})::String
    groups = _group_by_top(specs)
    tops = sort(collect(keys(groups)))
    io = IOBuffer()
    println(io, "#compdef friedman")
    println(io, "# Friedman-cli zsh completion (generated)")
    println(io, "_friedman() {")
    println(io, "  local -a commands")
    println(io, "  commands=(")
    for top in tops
        println(io, "    '$top'")
    end
    println(io, "    'repl'")
    println(io, "  )")
    println(io, "  _describe 'command' commands")
    println(io, "}")
    println(io, "_friedman \"\$@\"")
    return String(take!(io))
end

function _fish_completion(specs::Vector{Friedman.CommandSpec})::String
    groups = _group_by_top(specs)
    tops = sort(collect(keys(groups)))
    io = IOBuffer()
    println(io, "# Friedman-cli fish completion (generated)")
    for top in tops
        println(io, "complete -c friedman -n \"__fish_use_subcommand\" -a $top")
    end
    println(io, "complete -c friedman -n \"__fish_use_subcommand\" -a repl")
    return String(take!(io))
end

# ── Write / check ─────────────────────────────────────────────

function _write_or_check(path::String, content::String; check::Bool)
    mkpath(dirname(path))
    if check
        if !isfile(path)
            @error "missing generated file" path
            return false
        end
        old = read(path, String)
        if replace(old, "\r\n" => "\n") != replace(content, "\r\n" => "\n")
            @error "stale generated file" path
            return false
        end
        return true
    else
        open(path, "w") do io
            write(io, content)
        end
        println("wrote $path")
        return true
    end
end

function _patch_claude_md(block::String; check::Bool)
    path = joinpath(ROOT, "CLAUDE.md")
    isfile(path) || return true  # gitignored / absent in CI — skip
    text = read(path, String)
    begin_m = "<!-- BEGIN GENERATED"
    end_m = "<!-- END GENERATED -->"
    bi = findfirst(begin_m, text)
    ei = findfirst(end_m, text)
    if isnothing(bi) || isnothing(ei)
        # append section
        new_text = text * "\n\n## Generated Inventory\n\n" * block * "\n"
    else
        # replace from BEGIN through END inclusive
        start_i = first(bi)
        end_i = last(ei)
        new_text = text[1:start_i-1] * block * text[end_i+1:end]
    end
    if check
        return replace(text, "\r\n" => "\n") == replace(new_text, "\r\n" => "\n")
    end
    open(path, "w") do io
        write(io, new_text)
    end
    println("updated $path generated block")
    return true
end

function main()
    specs = _all_specs()
    @info "registry leaves" count=length(specs)
    ok = true

    # overview
    overview_path = joinpath(ROOT, "docs", "src", "commands", "overview.md")
    ok &= _write_or_check(overview_path, _overview_md(specs); check=CHECK)

    # per-top pages
    gen_dir = joinpath(ROOT, "docs", "src", "commands", "generated")
    groups = _group_by_top(specs)
    for top in sort(collect(keys(groups)))
        path = joinpath(gen_dir, "$top.md")
        ok &= _write_or_check(path, _top_page(top, groups[top]); check=CHECK)
    end

    # completions
    comp_dir = joinpath(ROOT, "completions")
    ok &= _write_or_check(joinpath(comp_dir, "friedman.bash"), _bash_completion(specs); check=CHECK)
    ok &= _write_or_check(joinpath(comp_dir, "friedman.zsh"), _zsh_completion(specs); check=CHECK)
    ok &= _write_or_check(joinpath(comp_dir, "_friedman.fish"), _fish_completion(specs); check=CHECK)

    if DO_CLAUDE
        ok &= _patch_claude_md(_claude_block(specs); check=CHECK)
    end

    if CHECK
        if ok
            println("generate_cli_reference: OK (up to date)")
            exit(0)
        else
            println(stderr, "generate_cli_reference: STALE — run: julia --project docs/generate_cli_reference.jl")
            exit(1)
        end
    end
end

main()
