#!/usr/bin/env julia
# Plot-recipe drift gate (#95).
#
# The CLI's plot flags are hand-verified per leaf against the pinned MEMs'
# `plot_result` recipes (the W5/#95 audit + per-wave sweeps; the standing rule
# is "only advertise --plot when a real recipe exists — verify per leaf, never
# bulk-add on a type-name match"). What that discipline cannot catch is DRIFT:
# a MEMs bump that removes a recipe silently breaks every leaf advertising it
# (typed exit 5 via the `_maybe_plot` net, but still a broken leaf), and one
# that adds recipes silently grows the sweep-A backlog.
#
# This tool derives the real receiver-type list by reflection and compares it
# against the committed baseline for the pin:
#   REMOVED  → audit every leaf that plots this type; strip its flags or fix.
#   ADDED    → sweep-A candidate; verify per leaf before advertising --plot.
#
# Usage (repo root, real MEMs in project env):
#   julia --project test/tools/check_plot_coverage.jl            # gate (CI/bump)
#   julia --project test/tools/check_plot_coverage.jl --update   # after the audit
#
# Run at every MEMs version bump (C038 protocol); regenerate the baseline with
# --update only AFTER the drift has been audited and the CLI surface adjusted.

using Pkg
Pkg.activate(joinpath(@__DIR__, "..", ".."))
using MacroEconometricModels

const BASELINE_PATH = joinpath(@__DIR__, "plot_receivers.txt")

"""Receiver type NAMES of every real `plot_result` method (Union members counted
individually; parametric receivers reduced to their base name)."""
function receiver_names()
    names = Set{String}()
    for m in methods(MacroEconometricModels.plot_result)
        sig = m.sig
        while sig isa UnionAll
            sig = sig.body
        end
        length(sig.parameters) >= 2 || continue
        t = sig.parameters[2]
        t isa Core.TypeofBottom && continue
        members = try
            Base.uniontypes(t)
        catch
            continue
        end
        for u in members
            b = u
            while b isa UnionAll
                b = b.body
            end
            b isa DataType || continue
            b === Any && continue
            push!(names, string(nameof(b)))
        end
    end
    return names
end

function main()
    current = receiver_names()
    mems_v = pkgversion(MacroEconometricModels)
    if "--update" in ARGS
        open(BASELINE_PATH, "w") do io
            println(io, "# plot_result receiver types at MacroEconometricModels $(mems_v)")
            println(io, "# Regenerated by check_plot_coverage.jl --update AFTER auditing drift (#95).")
            foreach(n -> println(io, n), sort!(collect(current)))
        end
        println("wrote baseline ($(length(current)) receiver types) → $BASELINE_PATH")
        return 0
    end

    isfile(BASELINE_PATH) || begin
        println("FAIL: no baseline at $BASELINE_PATH — run with --update on the audited pin")
        return 1
    end
    baseline = Set{String}(l for l in readlines(BASELINE_PATH)
                           if !isempty(l) && !startswith(l, "#"))
    removed = sort!(collect(setdiff(baseline, current)))
    added = sort!(collect(setdiff(current, baseline)))

    println("plot_result receivers: baseline $(length(baseline)), " *
            "current $(length(current)) (MEMs $(mems_v))")
    if isempty(removed) && isempty(added)
        println("PASS: no recipe drift against the baseline")
        return 0
    end
    for n in removed
        println("REMOVED: $n — every CLI leaf plotting this type is now broken; " *
                "audit and strip/repair its --plot flags before updating the baseline")
    end
    for n in added
        println("ADDED: $n — sweep-A candidate; verify per leaf (run --plot-save " *
                "against real MEMs) before advertising --plot")
    end
    println("FAIL: recipe drift — audit the leaves above, then rerun with --update")
    return 1
end

exit(main())
